bus.broker=rabbit

# Kafka
bus.kafka.bootstrap=localhost:9092
bus.kafka.groupId=bus-demo

# Rabbit
bus.rabbit.host=localhost
bus.rabbit.port=5672
bus.rabbit.user=guest
bus.rabbit.pass=guest
bus.rabbit.vhost=/
# Common
bus.serviceName=unknown-service
